/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_events_get"];
        put?: never;
        /**
         * Create Event
         * @description Create an Operational Event. Validates asset existence, enum source (by
         *     pydantic), and symptom membership against the curated map (D-011).
         */
        post: operations["create_event_api_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}/dossier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Dossier
         * @description Idempotent: an existing dossier is returned untouched (its Shared Context
         *     is frozen, P4); otherwise assemble synchronously and set status per
         *     REASONING_ENABLED.
         */
        post: operations["create_dossier_api_events__event_id__dossier_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dossiers/{dossier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dossier */
        get: operations["get_dossier_api_dossiers__dossier_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dossiers/{dossier_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Dossier */
        get: operations["stream_dossier_api_dossiers__dossier_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dossiers/{dossier_id}/evidence/{claim_ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evidence
         * @description Evidence Strength breakdown for a claim (backend explainability, P8).
         */
        get: operations["get_evidence_api_dossiers__dossier_id__evidence__claim_ref__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dossiers/{dossier_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Dossier
         * @description Contextual Q&A scoped to frozen dossier context only (FR-9, P1/P4).
         */
        post: operations["chat_dossier_api_dossiers__dossier_id__chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get App Config */
        get: operations["get_app_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/wo/{wo_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work Order */
        get: operations["get_work_order_api_sources_wo__wo_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/chunk/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chunk */
        get: operations["get_chunk_api_sources_chunk__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/file/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get File
         * @description Stream a rendered PDF from the read-only dataset mount (react-pdf source).
         */
        get: operations["get_file_api_sources_file__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assets */
        get: operations["list_assets_api_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{tag}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset */
        get: operations["get_asset_api_assets__tag__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppConfig */
        AppConfig: {
            /** Downtime Cost Per Hour Inr */
            downtime_cost_per_hour_inr: number;
            /** Downtime Cost Label */
            downtime_cost_label: string;
        };
        /** AssetProfile */
        AssetProfile: {
            /** Asset Id */
            asset_id: number;
            /** Tag */
            tag: string;
            /** Name */
            name: string;
            /** Asset Class */
            asset_class: string;
            /** Manufacturer */
            manufacturer: string;
            /** Model */
            model: string;
            /** Plant */
            plant: string;
            /** Unit */
            unit: string;
            /** Area */
            area: string;
            /** Service Duty */
            service_duty: string;
            /** Criticality */
            criticality: string;
            /** Installed On */
            installed_on: string | null;
        };
        /** AssetSummary */
        AssetSummary: {
            /** Asset Id */
            asset_id: number;
            /** Tag */
            tag: string;
            /** Name */
            name: string;
            /** Asset Class */
            asset_class: string;
            /** Plant */
            plant: string;
            /** Unit */
            unit: string;
            /** Area */
            area: string;
            /** Service Duty */
            service_duty: string;
            /** Criticality */
            criticality: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Question */
            question: string;
            /** History */
            history?: components["schemas"]["ChatTurn"][];
        };
        /** ChatResponse */
        ChatResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: string[];
            /** Refused */
            refused: boolean;
            /** Grounding */
            grounding?: ("evidenced" | "hypothesis") | null;
        };
        /** ChatTurn */
        ChatTurn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Text */
            text: string;
        };
        /** ChunkRecord */
        ChunkRecord: {
            /** Chunk Id */
            chunk_id: number;
            /** Document Id */
            document_id: number;
            /** Doc Type */
            doc_type: string;
            /** Page */
            page: number;
            /** Section Ref */
            section_ref: string | null;
            /** Content */
            content: string;
            /**
             * Retrieval Channel
             * @enum {string}
             */
            retrieval_channel: "semantic" | "lexical" | "both";
            /** Citation Id */
            readonly citation_id: string;
        };
        /** ChunkSource */
        ChunkSource: {
            /** Chunk Id */
            chunk_id: number;
            /** Citation Id */
            citation_id: string;
            /** Document Id */
            document_id: number;
            /** Doc Type */
            doc_type: string;
            /** Document Title */
            document_title: string;
            /** Page */
            page: number;
            /** Section Ref */
            section_ref?: string | null;
            /** Content */
            content: string;
            /** File Url */
            file_url: string;
        };
        /**
         * Criticality
         * @enum {string}
         */
        Criticality: "A" | "B" | "C";
        /** DegradedInfo */
        DegradedInfo: {
            /**
             * Reason
             * @enum {string}
             */
            reason: "reasoning_disabled" | "llm_failure" | "node_failure";
            /**
             * Deterministic Available
             * @default true
             */
            deterministic_available: boolean;
        };
        /**
         * DossierResponse
         * @description Full dossier JSON (GET) and the ``context_ready`` SSE payload share this
         *     shape. ``context`` is the frozen deterministic Shared Context; ``sections``
         *     holds validated AI outputs (null until M6); ``degraded`` is set when the
         *     reasoning layer did not (or could not) run.
         */
        DossierResponse: {
            /** Dossier Id */
            dossier_id: number;
            /** Event Id */
            event_id: number;
            /** Status */
            status: string;
            /** Reasoning Enabled */
            reasoning_enabled: boolean;
            /** Evidence Pool Size */
            evidence_pool_size: number;
            context?: components["schemas"]["SharedContext"] | null;
            /** Sections */
            sections?: {
                [key: string]: unknown;
            } | null;
            degraded?: components["schemas"]["DegradedInfo"] | null;
        };
        /**
         * EventCreate
         * @description Canonical Operational Event intake (P6/D-011). ``source`` and
         *     ``criticality`` are enum-validated by pydantic; ``asset_tag`` existence and
         *     ``symptom_category`` membership are validated in the handler.
         */
        EventCreate: {
            /** Asset Tag */
            asset_tag: string;
            source: components["schemas"]["EventSource"];
            /** Symptom Category */
            symptom_category: string;
            /** Note */
            note?: string | null;
            criticality: components["schemas"]["Criticality"];
        };
        /** EventInfo */
        EventInfo: {
            /** Event Id */
            event_id: number;
            /** Asset Tag */
            asset_tag: string;
            /** Source */
            source: string;
            /** Symptom Category */
            symptom_category: string;
            /** Note */
            note: string | null;
            /** Criticality */
            criticality: string;
            /** Status */
            status: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /**
         * EventSource
         * @enum {string}
         */
        EventSource: "manual" | "simulated" | "integration";
        /**
         * EventSummary
         * @description Event board row + single-event view.
         */
        EventSummary: {
            /** Id */
            id: number;
            /** Asset Tag */
            asset_tag: string;
            /** Asset Name */
            asset_name: string;
            /** Plant */
            plant: string;
            /** Unit */
            unit: string;
            /** Source */
            source: string;
            /** Symptom Category */
            symptom_category: string;
            /** Note */
            note: string | null;
            /** Criticality */
            criticality: string;
            /** Status */
            status: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Dossier Id */
            dossier_id?: number | null;
        };
        /** EvidenceBreakdown */
        EvidenceBreakdown: {
            /** Claim Ref */
            claim_ref: string;
            /** Tier */
            tier: string;
            /** Score */
            score: number;
            /** Components */
            components: {
                [key: string]: unknown;
            };
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PatternStat */
        PatternStat: {
            /** Failure Mode */
            failure_mode: string;
            /** Occurrences */
            occurrences: number;
            /** Span Months */
            span_months: number;
            /** Total Downtime Hours */
            total_downtime_hours: number;
            /** Distinct Phrasings */
            distinct_phrasings: string[];
            /** Asset Tags */
            asset_tags: string[];
        };
        /** SharedContext */
        SharedContext: {
            event: components["schemas"]["EventInfo"];
            asset_profile: components["schemas"]["AssetProfile"];
            /** Failure History */
            failure_history: components["schemas"]["WorkOrderRecord"][];
            /** Sister Incidents */
            sister_incidents: components["schemas"]["SisterIncident"][];
            /** Manual Chunks */
            manual_chunks: components["schemas"]["ChunkRecord"][];
            /** Sop Chunks */
            sop_chunks: components["schemas"]["ChunkRecord"][];
            /** Report Chunks */
            report_chunks: components["schemas"]["ChunkRecord"][];
            /** Pattern Stats */
            pattern_stats: components["schemas"]["PatternStat"][];
            /** Evidence Pool */
            evidence_pool: string[];
            /**
             * Assembled At
             * Format: date-time
             */
            assembled_at: string;
            /**
             * Content Hash
             * @default
             */
            content_hash: string;
        };
        /** SisterIncident */
        SisterIncident: {
            /** Wo Number */
            wo_number: string;
            /** Asset Tag */
            asset_tag: string;
            /** Asset Name */
            asset_name: string;
            /** Failure Mode Code */
            failure_mode_code: string | null;
            /**
             * Opened On
             * Format: date
             */
            opened_on: string;
            /** Closed On */
            closed_on: string | null;
            /** Raw Description */
            raw_description: string;
            /** Downtime Hours */
            downtime_hours: number | null;
            /** Citation Id */
            readonly citation_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkOrderRecord */
        WorkOrderRecord: {
            /** Wo Number */
            wo_number: string;
            /** Asset Tag */
            asset_tag: string;
            /**
             * Opened On
             * Format: date
             */
            opened_on: string;
            /** Closed On */
            closed_on: string | null;
            /** Raw Description */
            raw_description: string;
            /** Actions Taken */
            actions_taken: string | null;
            /** Downtime Hours */
            downtime_hours: number | null;
            /** Failure Mode Code */
            failure_mode_code: string | null;
            /** Citation Id */
            readonly citation_id: string;
        };
        /** WorkOrderSource */
        WorkOrderSource: {
            /** Wo Number */
            wo_number: string;
            /** Citation Id */
            citation_id: string;
            /** Asset Tag */
            asset_tag: string;
            /** Asset Name */
            asset_name: string;
            /** Opened On */
            opened_on?: string | null;
            /** Closed On */
            closed_on?: string | null;
            /** Raw Description */
            raw_description: string;
            /** Actions Taken */
            actions_taken?: string | null;
            /** Downtime Hours */
            downtime_hours?: number | null;
            /** Failure Mode Code */
            failure_mode_code?: string | null;
            /** Failure Mode Name */
            failure_mode_name?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_event_api_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dossier_api_events__event_id__dossier_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DossierResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dossier_api_dossiers__dossier_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dossier_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DossierResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_dossier_api_dossiers__dossier_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dossier_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_dossiers__dossier_id__evidence__claim_ref__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dossier_id: number;
                claim_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceBreakdown"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_dossier_api_dossiers__dossier_id__chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dossier_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_app_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
        };
    };
    get_work_order_api_sources_wo__wo_number__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                wo_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrderSource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chunk_api_sources_chunk__chunk_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chunk_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkSource"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_api_sources_file__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assets_api_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetSummary"][];
                };
            };
        };
    };
    get_asset_api_assets__tag__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
